apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhuus2mfe-nodejs 
  janus-idp.io/tekton: rhuus2mfe-nodejs
  backstage.io/kubernetes-id: rhuus2mfe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhuus2mfe-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml