apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rhuus2mfe-nodejs
  janus-idp.io/tekton: rhuus2mfe-nodejs
  backstage.io/kubernetes-id: rhuus2mfe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhuus2mfe-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
