apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhuus2mfe-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhuus2mfe-nodejs 
  name: rhuus2mfe-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rhuus2mfe-nodejs 
