apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhuus2mfe-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-bcaad7d93e.pysq.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:d65321bae64847cb24c83ec47eacaa5c34b2e9d0@sha256:69ad4d4ee0d91dc3988f6abc0e8518f94f6aa56e9658768755a08fc578009f9d
          name: container-image
